-- MySQL Script generated by MySQL Workbench
-- 10/06/14 16:32:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SUMGA
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SUMGA
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SUMGA` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `SUMGA` ;

-- -----------------------------------------------------
-- Table `SUMGA`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUMGA`.`Persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUMGA`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUMGA`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `tipoUsuario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `idPersona_idx` (`idPersona` ASC),
  CONSTRAINT `idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `SUMGA`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SUMGA`.`Depositos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SUMGA`.`Depositos` (
  `idDeposito` INT NOT NULL AUTO_INCREMENT,
  `cantidad` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `idUsuario` INT NOT NULL,
  INDEX `idUsuario_idx` (`idUsuario` ASC),
  PRIMARY KEY (`idDeposito`),
  CONSTRAINT `idUsuario`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `SUMGA`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
